config/routes.rb
Rails.application.routes.draw do
  namespace :transactions do
    resources :deposits
    resources :withdraws
    resources :transfers
  end
  
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
class Deposit < Transaction
  def create
    ActiveRecord::Base.transaction do
      self.save!
      self.update_balance
    rescue ActiveRecord::RecordInvalid => e
      raise ActiveRecord::Rollback
    end
  end

  def update_balance
    user.update! balance: user.balance + amount.to_i
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :from, :class_name => 'User', optional: true
  belongs_to :to, :class_name => 'User', optional: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

end

app/models/transfer.rb
class Transfer < Transaction
  validates :from_id, presence: true, numericality: true
  validates :to_id, presence: true, numericality: true
  validate :validate_sender_receiver

  def create
    ActiveRecord::Base.transaction do
      self.save!
      self.update_balance_sender
      self.update_balance_receiver
    rescue StandardError => e
      errors.add(:base, e.message) if self.errors.empty?
      raise ActiveRecord::Rollback
    end
  end

  def update_balance_sender
    @user = self.from
    @user.update! balance: @user.balance - amount.to_i
  end

  def update_balance_receiver
    @user = User.find to_id
    @user.update! balance: @user.balance + amount.to_i
  end

  def validate_sender_receiver
    if self.from.id == self.to_id
       errors.add(:from_id, "Cannot transfer to self")
    end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions
  validates :balance, presence: true, numericality: { greater_than_or_equal_to: 0, message: ": Your balance is not enough" }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/withdraw.rb
class Withdraw < Transaction
  def create
    ActiveRecord::Base.transaction do
      self.save!
      self.update_balance
    rescue ActiveRecord::RecordInvalid => e
      errors.add(:base, e.message) if self.errors.empty?
      raise ActiveRecord::Rollback
    end 
  end

  def update_balance
    user.update! balance: user.balance - amount.to_i
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/transactions/deposits_controller.rb
class Transactions::DepositsController < ApplicationController
  before_action :authenticate_user!

  def new
    @deposit = Deposit.new
  end

  def create
    @deposit = Deposit.new(deposit_params) do |d|
      d.user = current_user  
    end

    if @deposit.create
      flash[:notice] = 'deposit was successfully processed.'
      redirect_to transactions_deposit_path(@deposit)
    else
      flash.now[:alert] = @deposit.errors.empty? ? 'deposit Error' : @deposit.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def deposit_params
    params.require(:deposit).permit(:amount)
  end
end

app/controllers/transactions/transfers_controller.rb
class Transactions::TransfersController < ApplicationController
  before_action :authenticate_user!

  def new
    @transfer = Transfer.new
  end

  def create
    @transfer = Transfer.new(transfer_params) do |transfer|
      transfer.from = current_user  
      transfer.to_id = transfer_params[:to_id]
    end

    if @transfer.create
      flash[:notice] = 'transfer was successfully processed.'
      redirect_to transactions_transfer_path(@transfer)
    else
      flash.now[:alert] = @transfer.errors.empty? ? 'Transfer Error' : @transfer.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def transfer_params
    params.require(:transfer).permit(:amount, :to_id)
  end

end

app/controllers/transactions/withdraws_controller.rb
class Transactions::WithdrawsController < ApplicationController
  before_action :authenticate_user!

  def new
    @withdraw = Withdraw.new
  end

  def create
    @withdraw = Withdraw.new(withdraw_params) do |t|
      t.user = current_user  
    end

    if @withdraw.create
      flash[:notice] = 'Withdrawal was successfully processed.'
      redirect_to transactions_withdraw_path(@withdraw)
    else
      flash.now[:alert] = @withdraw.errors.empty? ? 'Withdraw Error' : @withdraw.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def withdraw_params
    params.require(:withdraw).permit(:amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section class="section">
    <div class="container">
        <h2 class="subtitle">
            Current balance:
            <%= current_user.balance %>
        </h2>
    </div>
</section>

app/views/layouts/_header.html.erb
<nav aria-label="main navigation" class="navbar" role="navigation">
    <div class="navbar-brand">
        <%= link_to 'Ewall', root_path, class: 'navbar-item' %>

        <a aria-expanded="false" aria-label="menu" class="navbar-burger burger" data-target="navbarBasicExample" role="button">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div class="navbar-menu" id="navbarBasicExample">
        <div class="navbar-start">

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    Transaction
                </a>

                <div class="navbar-dropdown">
                    <%= link_to  "Deposit", new_transactions_deposit_path, class: "navbar-item" %>
                    <%= link_to  "Withdraw", new_transactions_withdraw_path, class: "navbar-item" %>
                    <%= link_to  "Transfer", new_transactions_transfer_path, class: "navbar-item" %>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        Report an issue
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <% if user_signed_in? %>
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link">
                                Logged in as <%= current_user.email %>
                            </a>
                            <div class="navbar-dropdown">
                                <%= link_to 'Edit profile', edit_user_registration_path, class: "navbar-item" %>
                                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                            </div>
                        </div>
                    <% else %>
                        <%= link_to "Sign up", new_user_registration_path, :class => 'button is-primary'  %>
                        <%= link_to "Login", new_user_session_path, :class => 'button is-light'  %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="container">
  <div class="notification is-primary">
    <button class="delete"></button>
    <%= notice %>
  </div>
</div>
<% end %>
<% if alert %>
  <div class="container">
  <div class="notification is-warning">
    <button class="delete"></button>
    <%= alert %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ewallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/header" %>
    <%= render  "layouts/messages" %>
    <%= yield %>
  </body>
</html>

app/views/transactions/deposits/new.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-half">
                <h1 class="title">Form Deposit:</h1>
                <%= form_with model: @deposit, url: "/transactions/deposits",local: true, method: "post" do |f| %>
                    <div class="field">
                        <%= f.label 'amount', class: "label" %>
                        <div class="control">
                            <%= f.text_field :amount, class: "input" %>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <%= f.submit "Submit", class: 'button is-primary' %>
                        </div>
                    </div>
                <% end %>

            </div>
        </div>
    </div>
</section>

app/views/transactions/transfers/new.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-half">
                <h1 class="title">Form Transfer:</h1>
                <%= form_with model: @transfer, url: "/transactions/transfers",local: true, method: "post" do |f| %>
                    <div class="field">
                        <%= f.label 'amount', class: "label" %>
                        <div class="control">
                            <%= f.text_field :amount, class: "input" %>
                        </div>
                    </div>
                    <div class="field">
                        <%= f.label 'Transfer To', class: "label" %>
                        <div class="control">
                            <%= f.text_field :to_id, class: "input" %>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <%= f.submit "Submit", class: 'button is-primary' %>
                        </div>
                    </div>
                <% end %>

            </div>
        </div>
    </div>
</section>

app/views/transactions/transfers/show.html.erb
Current balance: <%= current_user.balance %>

app/views/transactions/withdraws/new.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-half">
                <h1 class="title">Form Withdraw:</h1>
                <%= form_with model: @withdraw, url: "/transactions/withdraws",local: true, method: "post" do |f| %>
                    <div class="field">
                        <%= f.label 'amount', class: "label" %>
                        <div class="control">
                            <%= f.text_field :amount, class: "input" %>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <%= f.submit "Submit", class: 'button is-primary' %>
                        </div>
                    </div>
                <% end %>

            </div>
        </div>
    </div>
</section>